### ISSUE TITLE
Could not resolve dependency during build

### ISSUE THREAD

**Issue by arnold-pinto** [bradmartin/nativescript-twitterbang#5]
Hi,

The android build fails with the following exception 

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_F0F1F2F3DebugApkCopy'.
   > Could not resolve hanks.xyz:smallbang-library:0.1.2.
     Required by:
         project :app
      > Could not resolve hanks.xyz:smallbang-library:0.1.2.
         > Could not get resource 'https://jcenter.bintray.com/hanks/xyz/smallbang-library/0.1.2/smallbang-library-0.1.2.pom'.
            > Could not GET 'https://jcenter.bintray.com/hanks/xyz/smallbang-library/0.1.2/smallbang-library-0.1.2.pom'.
               > jcenter.bintray.com

**Comment by fthuin** [comment]
Same here 
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_F0DebugApkCopy'.
   > Could not find hanks.xyz:smallbang-library:0.1.2.
     Required by:
         project :app
```

**Comment by bradmartin** [comment]
Hmmm... following the link it does return a 404 🤔  not sure right now. If someone can find what happened, if it moved or a different resource to pull in the lib then let me know and we can push a fix.

**Comment by arnold-pinto** [comment]
It appears that the package has moved to 

`pub.hanks:smallbang:1.2.2`

[https://bintray.com/hanks-zyh/maven/smallbang](url)

**Comment by HassanMoin** [comment]
Any solution to this problem guys ? 
Still getting the same error.

**Comment by bradmartin** [comment]
The old lib was unpublished I believe. I've just published version 2.0.0 of this plugin that uses the latest native lib and where it's not published `pub.hanks:smallbang...` This was a breaking change hence the major in the plugin incrementing to `2`.

It is not a layout similar to StackLayout, use it like that, assign a `tap` event on the TwitterBang layout and call `bang: Promise<void>` on the TwitterBang instance. All in the updated demo app and on README

**Comment by bharathkumar192** [comment]
still not able to find the solution to this one, can some one help?
